language: objective-c
osx_image: xcode7.3
before_script:
    - rvm use 2.2.5
    - gem install cucumber
    - gem install aruba
    - brew update
    - brew install carthage
script:
    - cucumber
    - sleep 5
