language: objective-c
osx_image: xcode7.3
before_install:
    - rvm use 2.2.5
before_script:
    - gem install cucumber
    - gem install aruba
    - brew update
    - brew outdated carthage || brew upgrade carthage
script:
    - cucumber
    - sleep 5
